services:
  # ------------------
  # SUPER BACKEND - 100% REAL NO FAKE
  # ------------------
  backend:
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    container_name: futback-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
  # ------------------
  db:
    env_file:
      - ./.env
    container_name: futback-db
    image: postgres:15-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U futmin -d futdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - futback-data:/var/lib/postgresql/data
    restart: always

volumes:
  futback-data: